"""ProductDetails table

Revision ID: 05804a1de142
Revises: 590561830064
Create Date: 2020-12-21 17:23:57.168333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05804a1de142'
down_revision = '590561830064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CompanyDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CompanyName', sa.String(length=255), nullable=False),
    sa.Column('Lat', sa.Float(), nullable=False),
    sa.Column('Long', sa.Float(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProductDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CompanyName', sa.String(length=255), nullable=False),
    sa.Column('Lat', sa.Float(), nullable=False),
    sa.Column('Long', sa.Float(), nullable=False),
    sa.Column('productname', sa.String(length=255), nullable=False),
    sa.Column('productprice', sa.Float(), nullable=False),
    sa.Column('productdescription', sa.Text(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('productdetails')
    op.drop_table('companydetails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companydetails',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('CompanyName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Lat', mysql.FLOAT(), nullable=False),
    sa.Column('Long', mysql.FLOAT(), nullable=False),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('productdetails',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('CompanyName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Lat', mysql.FLOAT(), nullable=False),
    sa.Column('Long', mysql.FLOAT(), nullable=False),
    sa.Column('productname', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('productprice', mysql.FLOAT(), nullable=False),
    sa.Column('productdescription', mysql.TEXT(), nullable=False),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ProductDetails')
    op.drop_table('CompanyDetails')
    # ### end Alembic commands ###
